name: Swift
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  push:
    branches: 
      - main 
    paths:
      - '**.swift'

  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Swift
      uses: actions/setup-swift@v2
      with: 
        swift-version: '5.5'
    - name: Build and Test
      run: |
        swift build
        swift test
      
