name: Metrics

on: 
  
 
 
 
 github-metrics:
     runs-on: ubuntu-latest
     permissions:
       contents: write
     steps:
       - name: LeetCode
         uses: lowlighter/metrics@master
         with:
           filename: metrics.plugin.leetcode.svg
           token: NOT_NEEDED
           base: ""
           plugin_leetcode: yes
           plugin_leetcode_sections: solved, skills, recent
           plugin_leetcode_limit_recent: 5
       - name: Most used (with details)
         uses: lowlighter/metrics@latest
         with:
           filename: metrics.plugin.languages.details.svg
           token: ${{ secrets.METRICS_TOKEN }}
           base: ""
           plugin_languages: yes
           plugin_languages_ignored: html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot
           plugin_languages_skipped: tywysocki/metrics, tywysocki/pytorch, tywysocki/openai-cookbook
           plugin_languages_details: bytes-size, percentage
           plugin_languages_colors: complementary
           plugin_languages_limit: 8
      
